<?xml version="1.0" encoding="UTF-8"?><testrun name="MultiplicationValidationTestException" project="Digit_Calculation" tests="4" started="4" failures="0" errors="0" ignored="0">
  <testsuite name="test.com.sviatlana.digit.validation.MultiplicationValidationTestException" time="0.006">
    <testsuite name="[0]" time="0.0">
      <testcase name="numberValidationTest[0]" classname="test.com.sviatlana.digit.validation.MultiplicationValidationTestException" time="0.0"/>
    </testsuite>
    <testsuite name="[1]" time="0.001">
      <testcase name="numberValidationTest[1]" classname="test.com.sviatlana.digit.validation.MultiplicationValidationTestException" time="0.001"/>
    </testsuite>
    <testsuite name="[2]" time="0.004">
      <testcase name="numberValidationTest[2]" classname="test.com.sviatlana.digit.validation.MultiplicationValidationTestException" time="0.004"/>
    </testsuite>
    <testsuite name="[3]" time="0.001">
      <testcase name="numberValidationTest[3]" classname="test.com.sviatlana.digit.validation.MultiplicationValidationTestException" time="0.001"/>
    </testsuite>
  </testsuite>
</testrun>
