package test.com.sviatlana.digit.validation;

import java.util.Arrays;
import java.util.Collection;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import com.sviatlana.digit.main.CustomException;

@RunWith(Parameterized.class)
public class MultiplicationValidationTestException {

	private int inputValue;
	private boolean expectedValue;
	private Class<? extends Exception> expectedException;
	private String expectedExceptionMsg;
	private int dg = 4;
	
	public MultiplicationValidationTestException (int input, boolean expected, Class<? extends Exception> expectedExc, String expectedMsg) {
		inputValue = input;
		expectedValue = expected;
		expectedException = expectedExc;
		expectedExceptionMsg = expectedMsg;
	}
	
	@Parameterized.Parameters
	public static Collection<Object[]> inputData() {
		return Arrays.asList (
			new Object[][] {
					{2222, true, null, null},
					{1111, true, null, null},
					{0, null, CustomException.class, "Zero is not sutable. Please run with a correct value."},
					{12345, null, CustomException.class, "The number of digits should be " + dg + ". Please run with a correct value."}
			}
		);
	}
	
	@Test
	
}
